"""
Test configuration and shared fixtures
"""

from pathlib import Path

import fakeredis
import pytest

from repositories import LocalDataRepository
from utils.cache import CacheManager
from utils.cache.simple_cache import SimpleCache

from .mock_eve_repository import MockEveRepository

# Path to tests directory
TESTS_DIR = Path(__file__).parent
REFERENCE_DIR = TESTS_DIR / "reference"


@pytest.fixture(scope="function")
def cache():
    """
    Fixture to provide a fakeredis cache for unit tests.
    Each test gets a fresh, isolated cache that is cleared after the test.
    """
    # Save current instance if it exists
    original_cache = CacheManager.get_instance()
    fake_redis_client = fakeredis.FakeStrictRedis(decode_responses=True)
    fake_cache = SimpleCache(redis_client=fake_redis_client, default_expiry_hours=24 * 30)
    CacheManager.initialize(fake_cache)

    try:
        yield fake_cache
    finally:
        # Clear cache after each unit test
        fake_cache.clear()
        # Restore original cache after test
        if original_cache:
            CacheManager.initialize(original_cache)
        else:
            CacheManager.initialize(None)


@pytest.fixture
def eve_repository():
    """Fixture to create a mock Eve repository for unit tests"""
    return MockEveRepository()


@pytest.fixture(scope="session")
def reference_data():
    """Loads reference data for tests"""
    import json

    reference_data = {}

    if REFERENCE_DIR.exists():
        for ref_file in REFERENCE_DIR.glob("*.json"):
            key = ref_file.stem
            try:
                with open(ref_file, encoding="utf-8") as f:
                    reference_data[key] = json.load(f)
            except json.JSONDecodeError:
                # Skip corrupted JSON files - they will be regenerated by tests
                continue

    return reference_data


@pytest.fixture
def local_data_repository(cache):
    return LocalDataRepository(cache)

